name: Test, Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Build and Setup Environment
        run: ./build.sh

      - name: Verify output
        run: |
          chmod +x test_scripts/verify_output.sh
          ./test_scripts/verify_output.sh 

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-readme
    if: ${{ needs.test-readme.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/2025cloud:${{ github.sha }}
