name: Test examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Build and Setup Environment
      run: |
        ./build.sh

    - name: Verify output
      run: |
        chmod +x test_scripts/verify_output.sh
        ./test_scripts/verify_output.sh 